### ISSUE TITLE
Handling more than one CFD transfer file

### ISSUE THREAD

**Issue by kowalskiw** [kowalskiw/fireeng-tools#12]
While running SAFIR thermal analysis using CFD results, only one transfer file can be used. There is possibility to use more than one file. It requires setting different section properties for elements located in different transfer domains. To run thermal analyses it is required to rename transfer files to 'cfd.txt' one by one. This process seems to be perfect candidate for the new script.

There is what `manycfds.py` should do:

1. Modifying mechanical input file.
2. Copying and changing thermal input files to 'CFD' thermal attack.
3. Iterating over transfer files:
-  finding the transfer domain boundaries;
- assigning modified in step (2) sections to elements that are located in the transfer domain boundaries;
- running thermal analyses of CFD-modified sections.

Wide testing is required to check possible and common errors.

The script should be used in `iso2nf.py` if more than one 'cfd*.txt' file is present.

Full documentation (in-the-file at least) should be developed.

**Comment by kowalskiw** [comment]
@zarooba01, we need some further development here to use this script as a part of `iso2nf.py`. The "standalone" version is working OK, on Windows machines at least.

We will need the function to be included at the beginning of `ThermalTEM.run()` and `ThermalTSH.run()`. So, it will assuming that `transfer_dir`=`config_dir` and checking if there are more than one `*radf_*_*.txt` file there. If not, it will just copy `*radf_*_*.txt` file changing its name to `cfd.txt`. If there is more than one transfer file we will need to use the main loop you made to calculate thermal response with all transfer files one by one.

Is it possible for you to do it?

**Comment by zarooba01** [comment]
Let's give it a try. If I have some problems I will tell you.

**Comment by kowalskiw** [comment]
Leaving it open until integration with `iso2nf.py` is achieved.

**Comment by kowalskiw** [comment]
I have reviewed `manycfds.py` and removed old version from `main` branch. Some to-dos are in the preamble of the script.

**Comment by kowalskiw** [comment]
The integration with `iso2nf.py` is done. Transfer files need to be in `config_dir/transfer_files`. 

Tested with one simple and one sophisticated configuration. More tests to be done.

It would be useful to pass `transfer_files` as an optional argument to specify the FDS results catalogue - no further copying would be required.
