### ISSUE TITLE
Unnecessary fixing of relaxations and copying of xml files from thermal analysis in iso2nf.py

### ISSUE THREAD

**Issue by kamil0301** [kowalskiw/fireeng-tools#16]
iso2nf.py repairs relaxations notation in xml files in thermal analysis, which is not needed. Only needed in mechanical analysis with relaxations.
This leads to copying sometimes multi-GB files for no reason.

**Comment by kowalskiw** [comment]
Thank you - I have fixed it commiting directly to the main branch (commit 7ef6e7328bd0db597f6760f0e31912de0294afdc).
